$(document).ready(
	function() 
	{
		$("#navdiv>ul>li").each(
			function()
			{
				$(this).hover(
					function()
					{
						$(this)
						     .css({backgroundColor:"#979797",color:"#FFFFFF"})
						     .find("a:first")
						     .css("color","#FFFFFF")
						     .find('i').addClass('icon-white');
						     if($(this).is("#father"))
						     {
						     	$("ul#about").slideDown(400);
						     	// 第一个子菜单
						     	$("ul#about>li").each(
						     		function()
						     		{
						     			$(this).hover(
						     				function()
						     				{
						     					$(this)
							     				.css({backgroundColor:"#979797",color:"#FFFFFF"})
							     				.find("a:first")
							     				.css("color","#FFFFFF");
							     				 if($(this).is("#son"))
							     				 {
							     				 	$("ul#weibo").slideDown(400);
							     				 	// 第二个子菜单
							     				 	$("ul#weibo>li").each(
							     				 		function()
							     				 		{
							     				 			$(this).hover(
							     				 				function()
							     				 				{
							     				 					$(this)
												     				.css({backgroundColor:"#979797",color:"#FFFFFF"})
												     				.find("a:first")
												     				.css("color","#FFFFFF");		
							     				 				},
							     				 				function()
							     				 				{
							     				 					$(this)
												     				.css({backgroundColor:"#E5E6E8",color:"#444444"})
												     				.find("a:first")
												     				.css("color","#777777");	
							     				 				}
							     				 			);
							     				 		}
							     				 	);
							     				 }
						     				},
						     				function()
						     				{
						     					$(this)
											     .css({backgroundColor:"#E5E6E8",color:"#444444"})
											     .find("a:first")
											     .css("color","#777777");
											     if($(this).is("#son"))
											     {
											     	$("ul#weibo").css('display',"none");
											     }
						     				}
						     			);
						     		}
						     	);
						     }
						     if($(this).is("#loginin"))
						     {
						     	$("ul#welcome").slideDown(400);
						     	$("ul#welcome>li").each(
						     		function()
						     		{
						     			$(this).hover(
						     				function()
						     				{
						     					$(this)
											     .css({backgroundColor:"#979797",color:"#FFFFFF"})
											      .find("a:first")
											     .css("color","#FFFFFF");
						     				},
						     				function()
						     				{
						     					$(this)
							     				.css({backgroundColor:"#E5E6E8",color:"#444444"})
							     				 .find("a:first")
							     				.css("color","#777777");	
						     				}
						     			);
						     		}
						     	);
						     }
					},
					function()
					{
						$(this)
						     .css({backgroundColor:"#E5E6E8",color:"#444444"})
						     .find("a:first")
						     .css("color","#777777")
						     .find('i').removeClass('icon-white');
						     if($(this).is("#father"))
						     {
						     	$("ul#about").css("display","none");
						     }
						     if($(this).is("#loginin"))
						     {
						     	$("ul#welcome").css("display","none");
						     }
					}
				);
			}
		);
		//登陆处理
		//弹出一个页面层 
		$('#loginlia').on('click', function()
		{ 
			$.layer({ 
			type: 1, 
			title: false, //不显示默认标题栏 
			shade: [0.5, '#000'], //显示遮罩  弹出时其它页面不可用
			shift: 'top', //从左动画弹出
			area: ['450px', '280px'], 
			page: {dom:"#loginForm"}	
			}); 
		}); 
		$("#cancelbtn").click(
			function()
			{
				window.location.href="index.php";
			}	
		); 
		 // 限制文章摘要字数
		$('.article-summary').each(
	                   function()
	                    {
	          		      var maxwidth=250;
	          		      if($(this).text().length>maxwidth)
	                        {
	                      		$(this).text($(this).text().substring(0,maxwidth));
	                      		$(this).text($(this).text()+'......');
	          	             }
		             }
	            );
	}
);